algo = input('Digite algo: ')
print('Qual a classe: ', type(algo))
print('É alfa: ', algo.isalpha())
print('É numérico: ', algo.isnumeric())
print('É alfanum: ', algo.isalnum())
print('É tudo maiúsculo: ', algo.isupper())
print('Capitalizando:', algo.capitalize())
print('É espaço: ', algo.isspace())
print('Está capitalizado: ', algo.istitle())
