nome = str(input('Qual é o seu nome? ')).strip()
print('Analisando seu nome...')
print('Seu nome em maiúsculas é {}'.format(nome.upper()))
print('Seu nome em minúsculas é {}'.format(nome.lower()))
print('Seu nome completo tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
corta = nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(corta[0], len(corta[0])))
