nome = str(input('Digite seu nome completo: ')).strip()
print('Prazer em te conhecer!')
separa = nome.split()
print('Seu primeiro nome é: {}'.format(separa[0]))
print('Seu último nome é: {}'.format(separa[-1]))
